Import the necessary libraries

In [1]:
import os
import pandas as pd
import numpy as np

Download the dataset from Kaggle and place the CSV in your working folder

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohamedasak/hospital-patient-readmission-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/mohamedasak/hospital-patient-readmission-dataset/1.archive...

100%|██████████| 128k/128k [00:00<00:00, 47.1MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/mohamedasak/hospital-patient-readmission-dataset/versions/1

In [3]:
path = "/root/.cache/kagglehub/datasets/mohamedasak/hospital-patient-readmission-dataset/versions/1"
print(os.listdir(path))

['hospital_readmission_dataset.csv']

Assign it to a variable called `df

In [4]:
df = pd.read_csv(f"{path}/hospital_readmission_dataset.csv")

See the first 10 entries

In [5]:
df.head(10)

,patient_id,admission_date,season,age,gender,region,primary_diagnosis,comorbidities_count,length_of_stay,treatment_type,medications_count,followup_visits_last_year,prev_readmissions,insurance_type,discharge_disposition,readmission_risk_score,label
0,P00001,2022-04-14,Spring,66,Male,South,Diabetes,5,6,Interventional,8,6,1,Medicare,Home Health,0.92,1
1,P00002,2021-09-19,Fall,55,Male,South,Diabetes,4,6,Interventional,6,4,3,Private,Home Health,0.88,1
2,P00003,2023-04-12,Spring,69,Female,West,Hypertension,6,8,Medical,9,6,2,Medicare,Skilled Nursing,0.97,1
3,P00004,2023-08-14,Summer,83,Male,South,Stroke,6,11,Medical,11,4,2,Medicare,Skilled Nursing,0.97,1
4,P00005,2021-11-05,Fall,54,Female,North,Stroke,4,10,Medical,6,2,1,Uninsured,Home Health,0.83,1
5,P00006,2021-04-15,Spring,54,Female,South,Diabetes,5,6,Medical,8,4,1,Uninsured,Home Health,0.75,1
6,P00007,2021-10-05,Fall,84,Female,West,Fracture,7,10,Surgical,12,6,3,Medicare,Skilled Nursing,0.97,1
7,P00008,2021-04-24,Spring,71,Female,South,Appendicitis,5,7,Medical,8,7,2,Medicare,Home Health,0.97,1
8,P00009,2021-12-20,Winter,50,Female,East,Hypertension,3,6,Interventional,4,2,1,Private,Home Health,0.46,0
9,P00010,2022-08-13,Summer,67,Male,West,Hypertension,6,5,Medical,10,4,2,Medicare,Skilled Nursing,0.97,1

What is the number of observations (rows) in the dataset?

In [6]:
df.shape[0]

8000

What is the number of columns in the dataset?

In [7]:
df.shape[1]

17

Print the name of all the column

In [8]:
##solution1:

In [9]:
df.columns

Index(['patient_id', 'admission_date', 'season', 'age', 'gender', 'region',
       'primary_diagnosis', 'comorbidities_count', 'length_of_stay',
       'treatment_type', 'medications_count', 'followup_visits_last_year',
       'prev_readmissions', 'insurance_type', 'discharge_disposition',
       'readmission_risk_score', 'label'],
      dtype='object')

In [10]:
#solution2:

In [11]:
pd.DataFrame(df.columns, columns=["column_name"])

                  column_name
0                  patient_id
1              admission_date
2                      season
3                         age
4                      gender
5                      region
6           primary_diagnosis
7         comorbidities_count
8              length_of_stay
9              treatment_type
10          medications_count
11  followup_visits_last_year
12          prev_readmissions
13             insurance_type
14      discharge_disposition
15     readmission_risk_score
16                      label

 How is the dataset indexed?

In [12]:
df.index

RangeIndex(start=0, stop=8000, step=1)

What are the data types of each column?

In [13]:
df.dtypes

patient_id                    object
admission_date                object
season                        object
age                            int64
gender                        object
region                        object
primary_diagnosis             object
comorbidities_count            int64
length_of_stay                 int64
treatment_type                object
medications_count              int64
followup_visits_last_year      int64
prev_readmissions              int64
insurance_type                object
discharge_disposition         object
readmission_risk_score       float64
label                          int64
dtype: object

Are there any missing values? Which columns have them, and how many per column?

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   patient_id                 8000 non-null   object
 1   admission_date             8000 non-null   object
 2   season                     8000 non-null   object
 3   age                        8000 non-null   int64
 4   gender                     8000 non-null   object
 5   region                     8000 non-null   object
 6   primary_diagnosis          8000 non-null   object
 7   comorbidities_count        8000 non-null   int64
 8   length_of_stay             8000 non-null   int64
 9   treatment_type             8000 non-null   object
 10  medications_count          8000 non-null   int64
 11  followup_visits_last_year  8000 non-null   int64
 12  prev_readmissions          8000 non-null   int64
 13  insurance_type             8000 non-null   object
 14  discharge_disposition      8000 non-null   object
 15  readmission_risk_score     8000 non-null   float64
 16  label                      8000 non-null   int64
dtypes: float64(1), int64(7), object(9)
memory usage: 1.0+ MB

In [15]:
for column in df.columns:
    print(f"Column '{column}': {df[column].isna().sum()} missing values")

Column 'patient_id': 0 missing values
Column 'admission_date': 0 missing values
Column 'season': 0 missing values
Column 'age': 0 missing values
Column 'gender': 0 missing values
Column 'region': 0 missing values
Column 'primary_diagnosis': 0 missing values
Column 'comorbidities_count': 0 missing values
Column 'length_of_stay': 0 missing values
Column 'treatment_type': 0 missing values
Column 'medications_count': 0 missing values
Column 'followup_visits_last_year': 0 missing values
Column 'prev_readmissions': 0 missing values
Column 'insurance_type': 0 missing values
Column 'discharge_disposition': 0 missing values
Column 'readmission_risk_score': 0 missing values
Column 'label': 0 missing values

Are there any duplicate rows in the dataset?

In [16]:
df.duplicated().sum()

np.int64(0)

Are there any duplicate columns in the dataset?

In [17]:
duplicate_columns = df.columns[df.columns.duplicated()]

if not duplicate_columns.empty:
    print(f"Found duplicate column names: {duplicate_columns.tolist()}")
else:
    print("No duplicate column names found.")

No duplicate column names found.

What is the target/label column for this dataset, and what are its possible values (e.g. readmitted: yes/no)?"]

In [18]:
df.label.unique()

array([1, 0])

 What percentage of patients were readmitted vs. not readmitted? Is the target balanced or imbalanced

In [19]:
df.label.value_counts(normalize=True)*100

label
1    77.2875
0    22.7125
Name: proportion, dtype: float64

What is the age range of patients (min, max, mean, median)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   patient_id                 8000 non-null   object
 1   admission_date             8000 non-null   object
 2   season                     8000 non-null   object
 3   age                        8000 non-null   int64
 4   gender                     8000 non-null   object
 5   region                     8000 non-null   object
 6   primary_diagnosis          8000 non-null   object
 7   comorbidities_count        8000 non-null   int64
 8   length_of_stay             8000 non-null   int64
 9   treatment_type             8000 non-null   object
 10  medications_count          8000 non-null   int64
 11  followup_visits_last_year  8000 non-null   int64
 12  prev_readmissions          8000 non-null   int64
 13  insurance_type             8000 non-null   object
 14  discharge_disposition      8000 non-null   object
 15  readmission_risk_score     8000 non-null   float64
 16  label                      8000 non-null   int64
dtypes: float64(1), int64(7), object(9)
memory usage: 1.0+ MB

In [21]:
df.age.mean()

np.float64(57.411625)

In [22]:
df.age.median()

57.0

In [23]:
df.age.min()

18

In [24]:
df.age.max()

95

What is the gender distribution in the dataset

In [25]:
df.gender.value_counts()

gender
Female    4184
Male      3816
Name: count, dtype: int64

In [26]:
gender_distribution_percent = df.gender.value_counts(normalize=True) * 100
for gender, percentage in gender_distribution_percent.items():
    print(f"{gender}: {percentage:.2f}%")

Female: 52.30%
Male: 47.70%

Which gender has a higher readmission rate?

In [27]:
df.groupby("gender")["label"].value_counts(normalize=True)

gender  label
Female  1        0.778920
        0        0.221080
Male    1        0.766247
        0        0.233753
Name: proportion, dtype: float64

What is the most common diagnosis / admission type in the dataset?

What is the average length of hospital stay? What is the longest stay recorded?

In [28]:
df.length_of_stay.mean()

np.float64(7.789125)

In [29]:
df.length_of_stay.max()

15

  Is there a relationship between length of stay and readmission (e.g. compare average length of stay for readmitted vs. non-readmitted patients)

In [30]:
df.groupby("label")["length_of_stay"].mean()

label
0    6.993946
1    8.022804
Name: length_of_stay, dtype: float64

What is the average number of medications and/or lab procedures per patient?:

In [32]:
#solution1:
df.groupby("patient_id")["medications_count"].mean()

patient_id
P00001     8.0
P00002     6.0
P00003     9.0
P00004    11.0
P00005     6.0
          ...
P07996    11.0
P07997     7.0
P07998     4.0
P07999    12.0
P08000    10.0
Name: medications_count, Length: 8000, dtype: float64

In [ ]:
#solution#:
average_medications_overall = df['medications_count'].mean()
print(f"Overall Average Medications per Patient: {average_medications_overall:.2f}")

    Bucket age into groups (e.g. 0-18, 19-35, 36-50, 51-65, 65+). Which age group has the highest readmission rate?

In [34]:
age_bins = [0, 18, 35, 50, 65, np.inf]
age_labels = ['0-18', '19-35', '36-50', '51-65', '65+']
df['age_group'] = pd.cut(df['age'], bins=age_bins, labels=age_labels, right=True)

readmission_rates_by_age = df.groupby('age_group')['label'].mean().sort_values(ascending=False)

print("Readmission rates by age group:")
print(readmission_rates_by_age)

highest_readmission_group = readmission_rates_by_age.index[0]
highest_rate = readmission_rates_by_age.iloc[0]

print(f"\nThe age group with the highest readmission rate is {highest_readmission_group} with a rate of {highest_rate:.2%}.")

Readmission rates by age group:
age_group
65+      0.953580
51-65    0.806726
36-50    0.629857
19-35    0.449788
0-18     0.292135
Name: label, dtype: float64

The age group with the highest readmission rate is 65+ with a rate of 95.36%.

/tmp/ipykernel_290/2646956592.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  readmission_rates_by_age = df.groupby('age_group')['label'].mean().sort_values(ascending=False)

Which numeric columns are most correlated with the readmission target? :

In [35]:
numeric_cols = df.select_dtypes(include=np.number).columns
correlation_matrix = df[numeric_cols].corr()['label'].sort_values(ascending=False)

print("Correlation of numeric columns with 'label' (Readmission Target):\n")
print(correlation_matrix)

Correlation of numeric columns with 'label' (Readmission Target):

label                        1.000000
readmission_risk_score       0.532056
comorbidities_count          0.392986
age                          0.384241
medications_count            0.354119
prev_readmissions            0.346626
followup_visits_last_year    0.298560
length_of_stay               0.223335
Name: label, dtype: float64

 Summarize the dataset with `.describe()`. What stands out (outliers, unusual ranges, skew)?

In [36]:
print(df.describe())

               age  comorbidities_count  length_of_stay  medications_count  \
count  8000.000000          8000.000000     8000.000000        8000.000000
mean     57.411625             4.318500        7.789125           7.475750
std      16.724388             1.358046        1.930252           2.287917
min      18.000000             1.000000        3.000000           2.000000
25%      46.000000             3.000000        6.000000           6.000000
50%      57.000000             4.000000        8.000000           8.000000
75%      69.000000             5.000000        9.000000           9.000000
max      95.000000            10.000000       15.000000          18.000000

       followup_visits_last_year  prev_readmissions  readmission_risk_score  \
count                8000.000000         8000.00000             8000.000000
mean                    3.638125            1.57250                0.776937
std                     1.630415            0.89196                0.219885
min                     0.000000            0.00000                0.070000
25%                     2.000000            1.00000                0.630000
50%                     4.000000            1.00000                0.860000
75%                     4.000000            2.00000                0.970000
max                    10.000000            5.00000                0.970000

             label
count  8000.000000
mean      0.772875
std       0.419000
min       0.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       1.000000