# Ex3 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
import os

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [ ]:
column_names = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='|', header=None, names=column_names)

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [ ]:
users = users.set_index('user_id')
display(users.head())

         age  gender  occupation  zip_code
user_id
user_id  age  gender  occupation  zip_code
1         24       M  technician     85711
2         53       F       other     94043
3         23       M      writer     32067
4         24       M  technician     43537

### Step 4. See the first 25 entries

In [ ]:
users.head(25)

         age  gender     occupation  zip_code
user_id
user_id  age  gender     occupation  zip_code
1         24       M     technician     85711
2         53       F          other     94043
3         23       M         writer     32067
4         24       M     technician     43537
5         33       F          other     15213
6         42       M      executive     98101
7         57       M  administrator     91344
8         36       M  administrator     05201
9         29       M        student     01002
10        53       M         lawyer     90703
11        39       F          other     30329
12        28       F          other     06405
13        47       M       educator     29206
14        45       M      scientist     55106
15        49       F       educator     97301
16        21       M  entertainment     10309
17        30       M     programmer     06355
18        35       F          other     37212
19        40       M      librarian     02138
20        42       F      homemaker     95660
21        26       M         writer     30068
22        25       M         writer     40206
23        30       F         artist     48197
24        21       F         artist     94533

### Step 5. See the last 10 entries

In [ ]:
users.tail(10)

        age gender     occupation zip_code
user_id
934      61      M       engineer    22902
935      42      M         doctor    66221
936      24      M          other    32789
937      48      M       educator    98072
938      38      F     technician    55038
939      26      F        student    33319
940      32      M  administrator    02215
941      20      M        student    97229
942      48      F      librarian    78209
943      22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [ ]:
users.shape[0]

944

### Step 7. What is the number of columns in the dataset?

In [ ]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [ ]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [ ]:
pd.DataFrame(users.columns, columns=['Columns'])

      Columns
0         age
1      gender
2  occupation
3    zip_code

### Step 9. How is the dataset indexed?

In [ ]:
users.index

Index(['user_id', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '934', '935', '936', '937', '938', '939', '940', '941', '942', '943'],
      dtype='object', name='user_id', length=944)

### Step 10. What is the data type of each column?

In [ ]:
users.dtypes

age           object
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [ ]:
users['occupation']

user_id
user_id       occupation
1             technician
2                  other
3                 writer
4             technician
               ...
939              student
940        administrator
941              student
942            librarian
943              student
Name: occupation, Length: 944, dtype: object

### Step 12. How many different occupations are in this dataset?

In [ ]:
users.occupation.unique()

array(['occupation', 'technician', 'other', 'writer', 'executive',
       'administrator', 'student', 'lawyer', 'educator', 'scientist',
       'entertainment', 'programmer', 'librarian', 'homemaker', 'artist',
       'engineer', 'marketing', 'none', 'healthcare', 'retired',
       'salesman', 'doctor'], dtype=object)

### Step 13. What is the most frequent occupation?

In [ ]:
users.occupation.value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
salesman          12
lawyer            12
none               9
homemaker          7
doctor             7
occupation         1
Name: count, dtype: int64

In [ ]:
users.occupation.value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

In [ ]:
# The difference between summarize the DataFrame (which usually refers to df.describe()) and summarize all columns (which refers to df.describe(include='all')) lies in the types of columns they describe.

# df.describe() (Summarize the DataFrame, by default): This method by default provides descriptive statistics only for the numerical columns in the DataFrame. It calculates statistics such as count, mean, standard deviation, minimum, maximum, and the quartile values (25%, 50%, 75%). It effectively ignores object type columns (like strings or categories).

# df.describe(include='all') (Summarize all columns): When you use include='all', the method will generate descriptive statistics for all columns, including both numerical and categorical (object/string) columns. For numerical columns, it provides the same statistics as df.describe(). For categorical columns, it provides statistics like the count of non-null values, the number of unique values, the most frequent value (top), and its frequency (freq).

### Step 14. Summarize the DataFrame.

In [ ]:
users_cleaned = users.iloc[1:].copy()
users_cleaned['age'] = pd.to_numeric(users_cleaned['age'])
display(users_cleaned.describe())

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [ ]:
display(users_cleaned.describe(include='all'))

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [ ]:
users.occupation.describe()

count         944
unique         22
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [ ]:
pd.to_numeric(users_cleaned['age']).mean()

np.float64(34.05196182396607)

### Step 18. What is the age with least occurrence?

In [ ]:
users.age.value_counts().tail(1)

age
73    1
Name: count, dtype: int64

In [ ]:
# describe() tells you what's in your data (statistical properties).
# info() tells you what your data is (structure, types, non-null counts).

In [ ]:
# .loc[] (Label-based indexing):

# loc primarily uses labels (index and column names) for selection.
# When you use loc, you are specifying the actual names of the rows and columns you want to retrieve.
# It can take a single label, a list of labels, a slice of labels (inclusive of both start and end labels), or a boolean array.
# Example: If your DataFrame's index consists of names and columns are 'Age', 'Gender', df.loc['Alice', 'Age'] would select Alice's age. A slice like df.loc['Alice':'Bob', 'Age'] would include data for both 'Alice' and 'Bob'.
# .iloc[] (Integer-location based indexing):

# iloc primarily uses integer positions (0-based indexing) for selection.
# When you use iloc, you are specifying the integer positions of the rows and columns you want to retrieve, just like you would with a Python list or NumPy array.
# It can take a single integer, a list of integers, or a slice of integers (exclusive of the end integer).
# Example: df.iloc[0, 1] would select the value at the first row (index 0) and second column (index 1). A slice like df.iloc[0:2, 1] would include data for rows 0 and 1, but exclude row 2.
# Key Differences Summarized:

# loc: Uses names/labels; slices are inclusive of the end label.
# iloc: Uses integer positions; slices are exclusive of the end integer (standard Python slicing).
# It's crucial to understand which one to use based on whether you're working with the actual labels of your data or their numerical positions.